### ISSUE TITLE
Binaries get installed with prefix

### ISSUE THREAD

**Issue by nickdex** [sirredbeard/nim_lang_snap#6]
Hi, I just installed nim from snapstore on brand new manjaro, it created all binaries with nim-lang prefix. 
It is different from behaviour on my arch linux where all binaries are (as expected) without prefix?
Can you please remove prefixes for stable builds?

**Comment by sirredbeard** [comment]
This is a feature of snaps.

**Comment by nickdex** [comment]
In that case, shouldn't it be same for arch linux? I get non-prefixed binaries in it

**Comment by sirredbeard** [comment]
When using snap?

**Comment by nickdex** [comment]
Yes, I followed instructions given for nim-lang page in snap website

**Comment by sirredbeard** [comment]
See https://github.com/sirredbeard/nim_lang_snap#aliases for help on aliasing nim to your preferred version of nim.

**Comment by nickdex** [comment]
Thanks :smile:

**Comment by mcarifio** [comment]
First, I understand this issue is closed (and should be). Second, ty for snapping nim. I don't know much about the language, but installing it easily helps the learning curve.

I'd like to suggest two additions:

* hack a more generalized aliasing approach that decouples the nim executables from a specific snap package version(see below).
* perhaps turn that command into a shell script (say) `nim-lang-aliases.sh`. I don't know enough snapology to know where to actually put it, but let's say it's `Somewhere/Appropriate`.

Here's my attempt for `nim-lang.aliases.sh`:
```bash
#!/usr/bin/env bash
for n in $(dirname $(which nim-lang.nim))/nim-lang.*; do b=$(basename $n); sudo alias $b ${b#nim-lang.}; done
```

Some cons:
* I'm polishing the diamond. If the executables in the snap package change, then you'll know it and update the `README.md` accordingly. I'm trading your direct knowledge of nim upstream for a consistent naming convention, e.g. `nim-lang.${name}`. You could just as well insert your bash command and a script would work as well. 
* It's more complicated than a static command (`which`? `dirname`? what?).
* It's bash specific.
* Nim itself probably won't add new "core binaries" very often.

Some pros:
* One less thing to track as you update the snap from upstream. If they add a new binary, you just sweep it in.
* Paves the way for a more general snap tool to "elevate" aliases in general.

Extract whatever value you see fit from this posting. For me it was a useful exercise in learning a little bit more about snap and some of it's conventions. Ty.
